import { beforeEach,afterEach,it,expect,vi } from 'vitest';
vi.mock('server-only',()=>({}));
const mocks=vi.hoisted(()=>({jar:new Map<string,string>(),saved:vi.fn(),previewRead:vi.fn(),previewSave:vi.fn(),previewRemove:vi.fn(),discovery:vi.fn(),receipt:vi.fn(),cookieSet:vi.fn()}));
vi.mock('next/headers',()=>({cookies:async()=>({get:(name:string)=>mocks.jar.has(name)?{value:mocks.jar.get(name)}:undefined,set:(name:string,value:string,options:unknown)=>{mocks.cookieSet(name,value,options);mocks.jar.set(name,value);},delete:(name:string)=>mocks.jar.delete(name)})}));
vi.mock('@/lib/medops/previews',()=>({readPreview:mocks.previewRead,savePreview:mocks.previewSave,removePreview:mocks.previewRemove}));
vi.mock('@/lib/medops/discovery',()=>({discovery:mocks.discovery}));
vi.mock('@/lib/medops/receipts',async original=>({...await original<typeof import('@/lib/medops/receipts')>(),saveReceipt:mocks.saved,receipt:mocks.receipt}));
import {config,seal,unseal,GRANT_COOKIE,medopsRequest} from '@/lib/medops/server';
import {NextResponse} from 'next/server';
import {GET,POST} from '@/app/api/medops/route';
import {GET as preview} from '@/app/api/medops/preview/route';
import {GET as callback} from '@/app/api/medops/connect/route';
const previewId='p'.repeat(43);
const fingerprint='a'.repeat(64),tender={externalTenderId:'a'.repeat(20),items:[{id:'one',equipment:'Ventilator',quantity:4},{id:'two',equipment:'Monitor',quantity:2}]};
const response={tenderId:'medops-id',url:'http://localhost:3000/tenders?record=medops-id',status:'ADDED',importedAt:'2026-10-07T10:00:00Z'};
const request=(data:unknown,origin='http://localhost:3001')=>new Request('http://localhost:3001/api/medops',{method:'POST',headers:{'Content-Type':'application/json',Origin:origin},body:JSON.stringify(data)});
beforeEach(()=>{vi.stubEnv('MEDOPS_API_URL','http://localhost:3000');vi.stubEnv('APP_URL','http://localhost:3001');vi.stubEnv('MEDOPS_INTEGRATION_SECRET','private-synthetic-server-secret-48-characters');vi.stubEnv('INTEGRATION_ENVIRONMENT','development');mocks.jar.clear();mocks.cookieSet.mockReset();mocks.saved.mockReset();mocks.receipt.mockReset();mocks.discovery.mockReset().mockResolvedValue({tender,fingerprint});mocks.previewRead.mockReset().mockResolvedValue({tender,fingerprint});mocks.previewSave.mockReset().mockResolvedValue(previewId);mocks.previewRemove.mockReset().mockResolvedValue(undefined);vi.spyOn(globalThis,'fetch').mockResolvedValue(Response.json(response));});
afterEach(()=>{vi.restoreAllMocks();vi.unstubAllEnvs();});
function connect(){mocks.jar.set(GRANT_COOKIE,seal({grant:'g'.repeat(43),expires:Date.now()+60000,environment:'development'}));}
it('never contacts MedOps for disconnected discovery visitors',async()=>{const result=await GET();expect((await result.json()).connected).toBe(false);expect(fetch).not.toHaveBeenCalled();expect(mocks.discovery).not.toHaveBeenCalled();});
it('rejects missing employee connection and cross-origin writes before discovery or MedOps calls',async()=>{expect((await POST(request({}))).status).toBe(401);connect();expect((await POST(request({},'https://other.example'))).status).toBe(403);expect(fetch).not.toHaveBeenCalled();expect(mocks.discovery).not.toHaveBeenCalled();});
it('seals connection cookies with integrity, expiration and environment isolation',()=>{const value=seal({grant:'g'.repeat(43),expires:Date.now()+60000,environment:'development'});expect(unseal(value)).toBeDefined();expect(unseal(value+'x')).toBeUndefined();expect(unseal(seal({expires:Date.now()-1,environment:'development'}))).toBeUndefined();expect(unseal(seal({expires:Date.now()+60000,environment:'production'}))).toBeUndefined();});
it('rejects confidential/extra fields and invalid item selection',async()=>{connect();expect((await POST(request({tenderId:tender.externalTenderId,previewId,selectedItemIds:['one'],fingerprint,price:123}))).status).toBe(400);expect((await POST(request({tenderId:tender.externalTenderId,previewId,selectedItemIds:['one','one'],fingerprint}))).status).toBe(400);expect(fetch).not.toHaveBeenCalled();});
it('constructs the server payload from discovery, signs it privately and persists only a confirmed receipt',async()=>{connect();const result=await POST(request({tenderId:tender.externalTenderId,previewId,selectedItemIds:['one'],fingerprint}));expect(result.status).toBe(200);const [url,options]=vi.mocked(fetch).mock.calls[0];expect(url).toBe('http://localhost:3000/api/integrations/tender-tracker/import');const payload=JSON.parse(String(options!.body));expect(payload).toEqual({grant:'g'.repeat(43),tender,selectedItemIds:['one']});expect((options!.headers as Record<string,string>)['x-medops-signature']).toHaveLength(64);expect(mocks.saved).toHaveBeenCalledOnce();expect(mocks.discovery).not.toHaveBeenCalled();expect(mocks.previewRemove).toHaveBeenCalledWith(previewId);expect(await result.text()).not.toContain('g'.repeat(43));});
it('source preview uses Tracker storage/discovery without any MedOps request',async()=>{connect();mocks.receipt.mockResolvedValue({...response,externalTenderId:tender.externalTenderId});const r=await preview(new Request('http://localhost:3001/api/medops/preview?tenderId='+tender.externalTenderId));expect(r.status).toBe(200);expect(fetch).not.toHaveBeenCalled();expect(mocks.receipt).toHaveBeenCalledWith(tender.externalTenderId);});
it('rejects stale previews before sending',async()=>{connect();expect((await POST(request({tenderId:tender.externalTenderId,previewId,selectedItemIds:['one'],fingerprint:'b'.repeat(64)}))).status).toBe(409);expect(fetch).not.toHaveBeenCalled();});
it('does not mark offline/failed handoffs successful and permits a safe retry',async()=>{connect();vi.mocked(fetch).mockRejectedValueOnce(Error('private network error details'));const failed=await POST(request({tenderId:tender.externalTenderId,previewId,selectedItemIds:['one'],fingerprint}));expect(failed.status).toBe(503);expect(await failed.text()).not.toContain('private network error');expect(mocks.saved).not.toHaveBeenCalled();expect((await POST(request({tenderId:tender.externalTenderId,previewId,selectedItemIds:['one'],fingerprint}))).status).toBe(200);});
it('reports a receipt-storage failure honestly and never exposes server secrets',async()=>{connect();mocks.saved.mockRejectedValueOnce(Error('private credential'));const r=await POST(request({tenderId:tender.externalTenderId,previewId,selectedItemIds:['one'],fingerprint}));expect(r.status).toBe(503);const text=await r.text();expect(text).toContain('accepted the handoff');expect(text).not.toContain('private credential');});
it('rejects unsafe confirmation links from an invalid remote response',async()=>{connect();vi.mocked(fetch).mockResolvedValueOnce(Response.json({...response,url:'https://attacker.example'}));expect((await POST(request({tenderId:tender.externalTenderId,previewId,selectedItemIds:['one'],fingerprint}))).status).toBe(503);expect(mocks.saved).not.toHaveBeenCalled();});
it('rejects callback state mismatch before exchanging any connection code',async()=>{const r=await callback(new Request('http://localhost:3001/api/medops/connect?state=bad&code='+'c'.repeat(43)));expect(r.status).toBe(401);expect(fetch).not.toHaveBeenCalled();});
it('fails closed without private integration credentials and for mixed environments',()=>{vi.stubEnv('MEDOPS_INTEGRATION_SECRET','');expect(()=>config()).toThrow('not configured');vi.stubEnv('MEDOPS_INTEGRATION_SECRET','x'.repeat(48));vi.stubEnv('MEDOPS_API_URL','https://production.example');expect(()=>config()).toThrow('environment');});
it('sanitizes permission failures without exposing response bodies',async()=>{vi.mocked(fetch).mockResolvedValueOnce(Response.json({error:'raw private upstream token'},{status:403}));await expect(medopsRequest('/api/integrations/tender-tracker/session',{})).rejects.toThrow('permission');});
it('enforces small JSON-only handoff requests before contacting MedOps',async()=>{connect();const wrongType=new Request('http://localhost:3001/api/medops',{method:'POST',headers:{Origin:'http://localhost:3001','Content-Type':'text/plain'},body:'{}'});expect((await POST(wrongType)).status).toBe(415);const oversized=new Request('http://localhost:3001/api/medops',{method:'POST',headers:{Origin:'http://localhost:3001','Content-Type':'application/json'},body:JSON.stringify({text:'x'.repeat(13000)})});expect((await POST(oversized)).status).toBe(413);expect(fetch).not.toHaveBeenCalled();});

it('rejects non-HTTP local URLs and requires HTTPS in preview',()=>{vi.stubEnv('MEDOPS_API_URL','ftp://localhost:3000');expect(()=>config()).toThrow('environment');vi.stubEnv('INTEGRATION_ENVIRONMENT','preview');vi.stubEnv('MEDOPS_API_URL','http://preview.example');vi.stubEnv('APP_URL','https://tracker.example');expect(()=>config()).toThrow('environment');});

it('expires host cookies with Secure and root path when a remote grant is revoked',async()=>{vi.stubEnv('NODE_ENV','production');connect();vi.mocked(fetch).mockResolvedValueOnce(Response.json({},{status:401}));expect((await GET()).status).toBe(401);expect(mocks.cookieSet).toHaveBeenCalledWith(GRANT_COOKIE,'',expect.objectContaining({secure:true,path:'/',maxAge:0}));const [name,value,options]=mocks.cookieSet.mock.calls[0];const emitted=new NextResponse();emitted.cookies.set(name,value,options);expect(emitted.headers.get('set-cookie')).toContain('Secure');expect(emitted.headers.get('set-cookie')).toContain('Path=/');expect(emitted.headers.get('set-cookie')).toContain('Max-Age=0');});
