import { describe,it,expect } from 'vitest';
import { mapDiscovery } from '@/lib/medops/mapping';
import { deduplicate } from '@/lib/tender/dedupe';
import type { Tender } from '@/types/tender';
const t:Tender={id:'a'.repeat(20),title:'Medical equipment tender',sourceId:'official',sourceName:'Official institution',sourceUrl:'https://hospital.gov.in/tender',region:'Punjab',procurementScope:'institution',status:'ACTIVE_LIKELY',categories:['VENTILATION'],brandMatches:[],matchedKeywords:[],confidence:1,fetchedAt:'2026-10-07T10:00:00Z',checkedAt:'2026-10-07T10:00:00Z'};
describe('minimal discovery mapping',()=>{
 it('preserves every structured item, quantity, category and item evidence independently',()=>{const mapped=mapDiscovery({...t,equipmentItems:[{id:'a',name:'Ventilator',quantity:4,category:'VENTILATION',sourceUrl:'https://hospital.gov.in/boq',sourceSheet:'Equipment',sourceRow:3},{id:'b',name:'Patient monitor',quantity:null,category:'PATIENT_MONITORING'}]},'https://tracker.example');expect(mapped.items).toHaveLength(2);expect(mapped.items[0]).toMatchObject({id:'a',equipment:'Ventilator',quantity:4,category:'VENTILATION',sourceSheet:'Equipment',sourceRow:3});expect(mapped.items[1].quantity).toBeNull();expect(mapped).not.toHaveProperty('manufacturerId');});
 it('does not invent missing deadlines, tender numbers, quantities or institutions',()=>{const mapped=mapDiscovery(t,'https://tracker.example');expect(mapped.items[0].quantity).toBeNull();expect(mapped.number).toBeUndefined();expect(mapped.institution).toBeUndefined();expect(mapped.deadline).toBeUndefined();});
 it('preserves existing structured BOQ rows and source positions instead of one generic item',()=>{const specification={equipmentTypes:[],sections:{quantity:[{field:'Quantity / line items',requirement:'Ventilator Quantity 2',quantity:'2',sourceDocument:'https://hospital.gov.in/boq',sourceLabel:'BOQ',sourceSheet:'Sheet1',sourceRow:3},{field:'Quantity / line items',requirement:'Monitor Quantity 4',quantity:'4',sourceDocument:'https://hospital.gov.in/boq',sourceLabel:'BOQ',sourceSheet:'Sheet1',sourceRow:4}]},documentSources:[{label:'BOQ',url:'https://hospital.gov.in/boq',type:'boq'}]} as unknown as Tender['specification'];const mapped=mapDiscovery({...t,specification},'https://tracker.example');expect(mapped.items.map(i=>i.quantity)).toEqual([2,4]);expect(mapped.items[1].equipment).toBe('Monitor Quantity 4');});
 it('maps a single explicit source quantity but ignores administrative quantity preferences',()=>{const specification={equipmentTypes:['VENTILATORS'],sections:{quantity:[{requirement:'Quantity: 04Nos.',quantity:'04',sourceDocument:'https://hospital.gov.in/nit',sourceLabel:'NIT',sourcePage:2},{requirement:'quantity for MII purchase preference'}]},documentSources:[]} as unknown as Tender['specification'];expect(mapDiscovery({...t,specification},'https://tracker.example').items[0]).toMatchObject({quantity:4,sourcePage:2});});
 it('never distributes a tender total among multiple equipment types',()=>{const specification={equipmentTypes:['VENTILATORS','PATIENT_MONITORS'],sections:{quantity:[{requirement:'Total Quantity 10',quantity:'10',sourceDocument:'https://hospital.gov.in/nit',sourceLabel:'NIT'}]},documentSources:[]} as unknown as Tender['specification'];expect(mapDiscovery({...t,specification},'https://tracker.example').items[0].quantity).toBeNull();});
 it('keeps source references and corrigenda without downloading documents',()=>{const mapped=mapDiscovery({...t,documents:[{label:'Official PDF',url:'https://hospital.gov.in/source.pdf'}],corrigenda:[{title:'Extended deadline',url:'https://hospital.gov.in/corrigendum',publishedDate:'2026-10-07',revisedClosingDate:'2026-11-01'}]},'https://tracker.example');expect(mapped.documents[0].url).toBe('https://hospital.gov.in/source.pdf');expect(mapped.revisions[0].title).toBe('Extended deadline');expect(mapped.sourceUpdatedAt).toBe('2026-10-07T00:00:00.000Z');});
 it('rejects credential-bearing and executable source URLs; emits plain source text',()=>{expect(()=>mapDiscovery({...t,sourceUrl:'https://user:password@hospital.gov.in'},'https://tracker.example')).toThrow('usable source');const mapped=mapDiscovery({...t,title:'<b>Ventilator</b>'},'https://tracker.example');expect(mapped.title).toBe('Ventilator');});
});

it('retains available structured source items when deduplication chooses a current generic mirror',()=>{const original={...t,tenderId:'SAME-1',equipmentItems:[{id:'1',name:'Ventilator',quantity:2},{id:'2',name:'Monitor',quantity:3}]};const mirror={...t,id:'b'.repeat(20),tenderId:'SAME-1',checkedAt:'2026-10-07T11:00:00Z'};expect(deduplicate([original,mirror]).tenders[0].equipmentItems).toHaveLength(2);});

it('keeps date-only closing deadlines at the end of the Indian day in handoffs and revisions',()=>{const mapped=mapDiscovery({...t,effectiveClosingDate:'2026-11-01',corrigenda:[{revisedClosingDate:'2026-11-02'}]},'https://tracker.example');expect(mapped.deadline).toBe('2026-11-01T18:29:59.999Z');expect(mapped.revisions[0].revisedClosingDate).toBe('2026-11-02T18:29:59.999Z');});
