'use client';
import { useState } from 'react';
import { useMedOps } from './Connection';
import type { DiscoveryTender } from '@/lib/medops/mapping';
type Receipt={tenderId:string;url:string;status:string;importedAt:string};
type Preview={previewId:string;tender:DiscoveryTender;fingerprint:string;receipt:Receipt|null};
export default function SendToMedOps({id}:{id:string}){
 const connection=useMedOps(),[preview,setPreview]=useState<Preview|null>(null),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[receipt,setReceipt]=useState<Receipt|null>(null);
 async function open(){setError('');setBusy(true);try{const r=await fetch('/api/medops/preview?tenderId='+encodeURIComponent(id));const data=await r.json();if(!r.ok)throw Error(data.error);setPreview(data);setSelected(data.tender.items.map((item:{id:string})=>item.id));setReceipt(data.receipt);}catch(e){setError(e instanceof Error?e.message:'Could not preview');}finally{setBusy(false);}}
 async function send(){if(!preview)return;setBusy(true);setError('');try{const r=await fetch('/api/medops',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({tenderId:id,previewId:preview.previewId,selectedItemIds:selected,fingerprint:preview.fingerprint})});const data=await r.json();if(!r.ok)throw Error(data.error);setReceipt(data);setPreview(null);}catch(e){setError(e instanceof Error?e.message:'Could not send');}finally{setBusy(false);}}
 return <div className="medops-handoff">{connection.connected?<button type="button" disabled={busy} onClick={()=>void open()}>{busy?'Working…':receipt?'Review / send source update':'Send to MedOps'}</button>:<a href="/api/medops/connect/start">Connect MedOps to send</a>}{receipt&&<p role="status">{receipt.status==='ADDED'?'Added to MedOps':receipt.status==='SOURCE_UPDATE_AVAILABLE'?'Source Update Available':'Already in MedOps'} · <a href={receipt.url} target="_blank" rel="noopener noreferrer">Open in MedOps ↗</a></p>}{error&&<p role="alert">{error} <button disabled={busy} onClick={()=>void open()}>Try again</button></p>}{preview&&<div className="medops-preview" role="dialog" aria-label="Send to MedOps preview"><h3>Send to MedOps</h3><p><strong>{preview.tender.number??preview.tender.bidNumber??'Tender number not provided'}</strong> · {preview.tender.institution??'Institution not provided'}</p><p>Deadline: {preview.tender.deadline?new Date(preview.tender.deadline).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'Not provided'} · Source: {preview.tender.sourceName}</p><p>Choose the relevant equipment lines. Unknown quantities remain for manual review in MedOps.</p>{preview.tender.items.map(item=><label key={item.id} className="medops-item"><input type="checkbox" checked={selected.includes(item.id)} onChange={e=>setSelected(e.target.checked?[...selected,item.id]:selected.filter(i=>i!==item.id))}/>{item.equipment} · Quantity: {item.quantity??item.quantityText??'Not provided'}{item.category?` · ${item.category}`:''}</label>)}<p>This sends source references only. New opportunities start Pending Review. No bid or commercial decisions are made.</p><button type="button" disabled={busy} onClick={()=>void send()}>{busy?'Sending…':'Confirm & Send'}</button> <button type="button" disabled={busy} onClick={()=>setPreview(null)}>Cancel</button></div>}{!connection.connected&&connection.error&&<small>{connection.error}</small>}</div>;
}
