import type { Institution } from "@/types/tender";
export const institutions: Institution[] = [
  {
    id: "pgimer",
    name: "Postgraduate Institute of Medical Education and Research, Chandigarh",
    shortName: "PGIMER Chandigarh",
    region: "Chandigarh",
    city: "Chandigarh",
    aliases: [
      "PGIMER",
      "PGI Chandigarh",
      "Postgraduate Institute of Medical Education and Research",
      "Postgraduate Institute of Medical and Education and Research",
    ],
    institutionType: "central-government",
    operationalStatus: "operational",
    sourceIds: ["cppp-pgimer"],
    officialUrl: "https://pgimer.edu.in",
  },
  {
    id: "gmch",
    name: "Government Medical College and Hospital Sector 32, Chandigarh",
    shortName: "GMCH Chandigarh",
    region: "Chandigarh",
    city: "Chandigarh",
    aliases: [
      "GMCH Chandigarh",
      "GMCH Sector 32",
      "Government Medical College Chandigarh",
      "Government Medical College and Hospital Chandigarh",
      "Government Medical College and Hospital Sector 32",
      "GMCH",
    ],
    institutionType: "state-government",
    operationalStatus: "operational",
    sourceIds: ["chandigarh-eproc"],
    officialUrl: "https://gmch.gov.in/tenders",
  },
  {
    id: "aiims-bathinda",
    name: "All India Institute of Medical Sciences Bathinda",
    shortName: "AIIMS Bathinda",
    region: "Punjab",
    city: "Bathinda",
    aliases: [
      "AIIMS Bathinda",
      "All India Institute of Medical Sciences Bathinda",
    ],
    institutionType: "central-government",
    operationalStatus: "operational",
    sourceIds: ["aiims-bathinda", "aiims-bathinda-open", "cppp-aiims-bathinda"],
    officialUrl: "https://www.aiimsbathinda.edu.in",
  },
  {
    id: "esic-ludhiana",
    name: "ESIC Medical College and Hospital Ludhiana",
    shortName: "ESIC Ludhiana",
    region: "Punjab",
    city: "Ludhiana",
    aliases: [
      "ESIC Ludhiana",
      "ESIC Model Hospital Ludhiana",
      "ESIC Model Hospital Bharat Nagar",
      "ESIC Medical College and Hospital Ludhiana",
      "Employees State Insurance Corporation Ludhiana",
    ],
    institutionType: "central-government",
    operationalStatus: "operational",
    sourceIds: ["esic", "cppp-esic"],
    officialUrl: "https://esic.gov.in/tenders",
  },
  {
    id: "pgi-ferozepur",
    name: "PGIMER Satellite Centre Ferozepur",
    shortName: "PGIMER Ferozepur",
    region: "Punjab",
    city: "Ferozepur",
    aliases: [
      "PGIMER Satellite Centre Ferozepur",
      "PGI Satellite Centre Ferozepur",
      "PGIMER Firozpur",
      "Ferozepur Satellite Centre",
      "Satellite Centre Ferozepur",
    ],
    institutionType: "central-government",
    operationalStatus: "operational",
    sourceIds: ["cppp-pgimer"],
    officialUrl: "https://pgimer.edu.in",
  },
  {
    id: "gmc-patiala",
    name: "Government Medical College and Rajindra Hospital Patiala",
    shortName: "GMC Patiala",
    region: "Punjab",
    city: "Patiala",
    aliases: [
      "Government Medical College Patiala",
      "GMC Patiala",
      "GMC PTA",
      "Rajindra Hospital",
      "Rajindera Hospital",
    ],
    institutionType: "state-government",
    operationalStatus: "operational",
    sourceIds: ["punjab-dmer", "gmc-patiala"],
    officialUrl: "https://tenders.gmcpatiala.edu.in/",
  },
  {
    id: "gmc-amritsar",
    name: "Government Medical College and Guru Nanak Dev Hospital Amritsar",
    shortName: "GMC Amritsar",
    region: "Punjab",
    city: "Amritsar",
    aliases: [
      "Government Medical College Amritsar",
      "GMC Amritsar",
      "Guru Nanak Dev Hospital",
      "GNDH",
      "Medical College Amritsar",
    ],
    institutionType: "state-government",
    operationalStatus: "operational",
    sourceIds: ["punjab-dmer", "gmc-amritsar"],
    officialUrl: "https://www.gmc.edu.in/notices",
  },
  {
    id: "ggsmch-faridkot",
    name: "Guru Gobind Singh Medical College and Hospital Faridkot",
    shortName: "GGSMCH Faridkot",
    region: "Punjab",
    city: "Faridkot",
    aliases: [
      "Guru Gobind Singh Medical College",
      "Guru Gobind Singh Medical Hospital",
      "Guru Gobind Singh Medical College and Hospital",
      "GGSMCH",
      "GGSMC",
      "BFUHS Faridkot",
    ],
    institutionType: "state-government",
    operationalStatus: "operational",
    sourceIds: ["bfuhs", "punjab-dmer"],
    officialUrl:
      "https://examination.bfuhsonline.ac.in/onlinetender/tenderview.aspx",
  },
  {
    id: "aims-mohali",
    name: "Dr B R Ambedkar State Institute of Medical Sciences Mohali",
    shortName: "AIMS Mohali",
    region: "Punjab",
    city: "Mohali",
    aliases: [
      "Dr B R Ambedkar State Institute of Medical Sciences",
      "Ambedkar State Institute of Medical Sciences",
      "AIMS Mohali",
      "AIMS SAS Nagar",
      "Ambedkar Mohali",
    ],
    institutionType: "state-government",
    operationalStatus: "operational",
    sourceIds: ["punjab-dmer"],
    officialUrl: "https://aimsmohali.punjab.gov.in/en/tenders/",
  },
  {
    id: "sims-hoshiarpur",
    name: "Shaheed Udham Singh State Institute of Medical Sciences Hoshiarpur",
    shortName: "SIMS Hoshiarpur",
    region: "Punjab",
    city: "Hoshiarpur",
    aliases: [
      "Shaheed Udham Singh State Institute of Medical Sciences",
      "Medical College Hoshiarpur",
      "SIMS Hoshiarpur",
    ],
    institutionType: "government-project",
    operationalStatus: "project-stage",
    sourceIds: ["punjab-dmer", "punjab-pidb"],
    officialUrl: "https://eproc.punjab.gov.in",
  },
  {
    id: "sims-kapurthala",
    name: "Shri Guru Nanak Dev Ji State Institute of Medical Sciences Kapurthala",
    shortName: "SIMS Kapurthala",
    region: "Punjab",
    city: "Kapurthala",
    aliases: [
      "Shri Guru Nanak Dev Ji State Institute of Medical Sciences",
      "Sri Guru Nanak Dev Ji State Institute of Medical Sciences",
      "Medical College Kapurthala",
      "SIMS Kapurthala",
    ],
    institutionType: "government-project",
    operationalStatus: "project-stage",
    sourceIds: ["punjab-dmer", "punjab-pidb"],
    officialUrl: "https://eproc.punjab.gov.in",
  },
  {
    id: "sangrur-project",
    name: "Sangrur Government Medical College and Teaching Hospital project",
    shortName: "Sangrur medical-college project",
    region: "Punjab",
    city: "Sangrur",
    aliases: [
      "Government Medical College Sangrur",
      "Medical College and Teaching Hospital Sangrur",
      "medical college at Sangrur",
    ],
    institutionType: "government-ppp-project",
    operationalStatus: "project-stage",
    sourceIds: ["punjab-pidb", "punjab-dmer"],
    officialUrl: "https://eproc.punjab.gov.in",
  },
  {
    id: "sbs-project",
    name: "SBS Nagar Government Medical College and Teaching Hospital project",
    shortName: "SBS Nagar medical-college project",
    region: "Punjab",
    city: "Nawanshahr",
    aliases: [
      "Government Medical College SBS Nagar",
      "Medical College and Teaching Hospital SBS Nagar",
      "Medical College Nawanshahr",
      "medical college at SBS Nagar",
      "medical college at Nawanshahr",
    ],
    institutionType: "government-ppp-project",
    operationalStatus: "project-stage",
    sourceIds: ["punjab-pidb", "punjab-dmer"],
    officialUrl: "https://eproc.punjab.gov.in",
  },
  {
    id: "malerkotla-project",
    name: "Government Medical College project Malerkotla",
    shortName: "Malerkotla medical-college project",
    region: "Punjab",
    city: "Malerkotla",
    aliases: [
      "Nawab Sher Khan Government Medical College",
      "Nawab Sher Khan State Institute of Medical Sciences",
      "Medical College Malerkotla",
      "medical college at Malerkotla",
    ],
    institutionType: "government-project",
    operationalStatus: "project-stage",
    sourceIds: ["punjab-dmer", "punjab-pidb"],
    officialUrl: "https://eproc.punjab.gov.in",
  },
  {
    id: "aiims-bilaspur",
    name: "All India Institute of Medical Sciences Bilaspur",
    shortName: "AIIMS Bilaspur",
    region: "Himachal Pradesh",
    city: "Bilaspur",
    aliases: [
      "AIIMS Bilaspur",
      "All India Institute of Medical Sciences Bilaspur",
      "AIIMS Bilaspur Himachal Pradesh",
      "AIIMS BLS",
      "AIIMBL",
      "AIIMS-BLS",
    ],
    institutionType: "central-government",
    operationalStatus: "operational",
    sourceIds: [
      "aiims-bilaspur-gem",
      "aiims-bilaspur-cppp", "cppp-aiims-bilaspur",
      "aiims-bilaspur-niq",
    ],
    officialUrl: "https://www.aiimsbilaspur.edu.in",
  },
  {
    id: "igmc-shimla",
    name: "Indira Gandhi Medical College and Hospital Shimla",
    shortName: "IGMC Shimla",
    region: "Himachal Pradesh",
    city: "Shimla",
    aliases: [
      "IGMC Shimla",
      "Indira Gandhi Medical College Shimla",
      "Indira Gandhi Medical College and Hospital Shimla",
      "IGMC and Hospital Shimla",
      "IGH Shimla",
      "Principal IGMC Shimla",
      "MS IGH Shimla",
      "IGMC",
    ],
    institutionType: "state-government",
    operationalStatus: "operational",
    sourceIds: ["hp-health", "hp-dmer", "hpmscl", "hp-pwd"],
    officialUrl: "https://www.igmcshimla.edu.in",
  },
  {
    id: "aimss-chamiana",
    name: "Atal Institute of Medical Super Specialities Chamiana",
    shortName: "AIMSS Chamiana",
    region: "Himachal Pradesh",
    city: "Chamiana",
    aliases: [
      "AIMSS Chamiana",
      "Atal Institute of Medical Super Specialities",
      "Atal Institute of Medical Super Specialties",
      "Chamiana Super Speciality Hospital",
      "Chamiana Super Specialty Hospital",
      "AIMSS Shimla",
      "Chamiana Shimla",
      "AIMSS",
    ],
    institutionType: "state-government",
    operationalStatus: "operational",
    sourceIds: ["hp-health", "hp-dmer", "hpmscl", "hp-pwd"],
    officialUrl: "https://hptenders.gov.in",
  },
  {
    id: "rpgmc-tanda",
    name: "Dr Rajendra Prasad Government Medical College Tanda",
    shortName: "Dr RPGMC Tanda",
    region: "Himachal Pradesh",
    city: "Tanda",
    aliases: [
      "Dr RPGMC Tanda",
      "RPGMC Tanda",
      "Dr Rajendra Prasad Government Medical College Tanda",
      "Dr Rajendra Prasad Govt Medical College Tanda",
      "Tanda Medical College",
      "Medical College Tanda",
      "RPGMC Kangra",
      "Tanda Kangra",
      "RPGMC",
    ],
    institutionType: "state-government",
    operationalStatus: "operational",
    sourceIds: ["hp-health", "hp-dmer", "hpmscl"],
    officialUrl: "https://rpgmc.ac.in",
  },
  {
    id: "slbsgmch-nerchowk",
    name: "Shri Lal Bahadur Shastri Government Medical College and Hospital Nerchowk",
    shortName: "SLBSGMCH Nerchowk",
    region: "Himachal Pradesh",
    city: "Nerchowk",
    aliases: [
      "SLBSGMC",
      "SLBSGMCH",
      "SLBSGMC Nerchowk",
      "SLBSGMCH Nerchowk",
      "Shri Lal Bahadur Shastri Government Medical College",
      "Sh Lal Bahadur Shastri Government Medical College",
      "Lal Bahadur Shastri Medical College Mandi",
      "Medical College Nerchowk",
      "Ner Chowk Medical College",
    ],
    institutionType: "state-government",
    operationalStatus: "operational",
    sourceIds: ["hp-health", "hp-dmer", "hpmscl", "slbsgmc"],
    officialUrl: "https://www.slbsgmchmandi.com/tender",
  },
  {
    id: "yspgmc-nahan",
    name: "Dr Yashwant Singh Parmar Government Medical College Nahan",
    shortName: "Dr YSPGMC Nahan",
    region: "Himachal Pradesh",
    city: "Nahan",
    aliases: [
      "Dr YSPGMC Nahan",
      "YSPGMC Nahan",
      "Dr Yashwant Singh Parmar Government Medical College",
      "Dr YS Parmar Government Medical College",
      "Government Medical College Nahan",
      "Medical College Nahan",
      "Nahan Medical College",
      "YSPGMC Sirmaur",
      "YSPGMC",
    ],
    institutionType: "state-government",
    operationalStatus: "operational",
    sourceIds: ["hp-health", "hp-dmer", "hpmscl"],
    officialUrl: "https://hptenders.gov.in",
  },
  {
    id: "jlngmc-chamba",
    name: "Pt Jawahar Lal Nehru Government Medical College Chamba",
    shortName: "Pt JLNGMC Chamba",
    region: "Himachal Pradesh",
    city: "Chamba",
    aliases: [
      "Pt JLNGMC Chamba",
      "JLNGMC Chamba",
      "Pt Jawahar Lal Nehru Government Medical College",
      "Pt Jawaharlal Nehru Government Medical College",
      "Government Medical College Chamba",
      "Medical College Chamba",
      "JLNGMC",
      "GMCC",
    ],
    institutionType: "state-government",
    operationalStatus: "operational",
    sourceIds: ["hp-health", "hp-dmer", "hpmscl"],
    officialUrl: "https://hptenders.gov.in",
  },
  {
    id: "rkgmc-hamirpur",
    name: "Dr Radhakrishnan Government Medical College Hamirpur",
    shortName: "Dr RKGMC Hamirpur",
    region: "Himachal Pradesh",
    city: "Hamirpur",
    aliases: [
      "Dr RKGMC Hamirpur",
      "RKGMC Hamirpur",
      "Dr Radhakrishnan Government Medical College",
      "Dr Radha Krishan Government Medical College",
      "Government Medical College Hamirpur",
      "Medical College Hamirpur",
      "RKGMC",
    ],
    institutionType: "state-government",
    operationalStatus: "operational",
    sourceIds: ["hp-health", "hp-dmer", "hpmscl"],
    officialUrl: "https://hptenders.gov.in",
  },
];
// DMER lists this society separately; do not conflate it with the district PPP project.
institutions.push({
  id: "mastuana-project",
  name: "Sant Baba Attar Singh State Institute of Medical Sciences Society, Mastuana Sahib",
  shortName: "Mastuana Sahib medical-institute project",
  region: "Punjab",
  city: "Mastuana Sahib",
  aliases: [
    "Sant Baba Attar Singh State Institute of Medical Sciences",
    "Mastuana Sahib medical college",
    "Mastuana Sahib medical institute",
  ],
  institutionType: "government-project",
  operationalStatus: "project-stage",
  sourceIds: ["punjab-dmer"],
  officialUrl:
    "https://punjab.gov.in/department-of-medical-education-and-research/",
  verificationUrl:
    "https://punjab.gov.in/department-of-medical-education-and-research/",
  note: "Listed by Punjab DMER; operational MBBS status is not established. Kept separate from the Sangrur district PPP project.",
});
